### ISSUE TITLE
Cannot Load dylib image

### ISSUE THREAD

**Issue by ethanm88** [ethanm88/spray-blocker#2]
I am getting the following runtime error when pulling the gclib library from the source location. Files that are missing are: "libgclib.dylib" and "libgclibo.dylib". However, both of these files do not ship with the gclib package, so this does not make sense. The only dylib images that I see are gclib.dylib and gclibo.dylib. I sourced the environment for these images as well as moved these images into the respective build folders.

**Comment by emendes801** [comment]
Update: work around found using the prior company packages which directly implemented the communication with the Galil controller. This missing image is still troubling and could be a problem later in development.
